Nome: Maria Eduarda Rezende Rodrigues
RA: 165873

In [1]:
import numpy as np
from fractions import Fraction

np.set_printoptions(precision=6, suppress=True)


Exercício 1

a)
$$\begin{cases}2x+y=7\\ x-3y=-5\end{cases}
\;\Rightarrow\;
\underbrace{\begin{bmatrix}2&1\\1&-3\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\y\end{bmatrix}}_{\mathbf{x}}=
\underbrace{\begin{bmatrix}7\\-5\end{bmatrix}}_{\mathbf{b}}$$

b)
$$\begin{cases}x+2y-z=2\\ 3x-y+2z=9\\ 2x+y+z=7\end{cases}
\;\Rightarrow\;
\underbrace{\begin{bmatrix}1&2&-1\\3&-1&2\\2&1&1\end{bmatrix}}_{A}
\underbrace{\begin{bmatrix}x\\y\\z\end{bmatrix}}_{\mathbf{x}}=
\underbrace{\begin{bmatrix}2\\9\\7\end{bmatrix}}_{\mathbf{b}}$$

Verificação computacional:

In [7]:
# --- Item (a) ---
A1a = np.array([[2, 1],
                [1, -3]], dtype=float)   # matriz dos coeficientes
b1a = np.array([7, -5], dtype=float)     # vetor independente

# --- Item (b) ---
A1b = np.array([[1,  2, -1],
                [3, -1,  2],
                [2,  1,  1]], dtype=float)
b1b = np.array([2, 9, 7], dtype=float)

print("1a)\nA =\n", A1a, "\nb =", b1a)
print("    solução (x, y)    =", np.linalg.solve(A1a, b1a), "  (exata: 16/7, 17/7)")
print("\n1b)\nA =\n", A1b, "\nb =", b1b)
print("    solução (x, y, z) =", np.linalg.solve(A1b, b1b))

1a)
A =
 [[ 2.  1.]
 [ 1. -3.]] 
b = [ 7. -5.]
    solução (x, y)    = [2.285714 2.428571]   (exata: 16/7, 17/7)

1b)
A =
 [[ 1.  2. -1.]
 [ 3. -1.  2.]
 [ 2.  1.  1.]] 
b = [2. 9. 7.]
    solução (x, y, z) = [2. 1. 2.]


Interpretação: em ambos os casos $\det A \neq 0$, logo cada sistema possui solução única. 
No item (a), $x = 16/7 \approx 2{,}2857$ e $y = 17/7 \approx 2{,}4286$; no item (b), $(x,y,z)=(2,1,2)$.

Exercício 2

$$\begin{cases}2x+y-z=8\\ -3x-y+2z=-11\\ -2x+y+2z=-3\end{cases}$$

Matriz aumentada inicial:
$$\left[\begin{array}{rrr|r}2&1&-1&8\\-3&-1&2&-11\\-2&1&2&-3\end{array}\right]$$

Etapa 1 — pivô $a_{11}=2$. Multiplicadores: $m_{21}=-3/2$, $m_{31}=-2/2=-1$.
$L_2\leftarrow L_2+\tfrac32 L_1$ e $L_3\leftarrow L_3+L_1$:
$$\left[\begin{array}{rrr|r}2&1&-1&8\\0&\tfrac12&\tfrac12&1\\0&2&1&5\end{array}\right]$$

Etapa 2 — pivô $a_{22}=\tfrac12$. Multiplicador: $m_{32}=2/(1/2)=4$.
$L_3\leftarrow L_3-4L_2$:
$$\left[\begin{array}{rrr|r}2&1&-1&8\\0&\tfrac12&\tfrac12&1\\0&0&-1&1\end{array}\right]$$

Substituição regressiva:
- $-z=1\Rightarrow z=-1$
- $\tfrac12 y+\tfrac12 z=1\Rightarrow \tfrac12 y=1+\tfrac12\Rightarrow y=3$
- $2x+y-z=8\Rightarrow 2x=8-3-1=4\Rightarrow x=2$

$$\boxed{(x,y,z)=(2,\,3,\,-1)}$$

Conferência: $2(2)+3-(-1)=8$ ✓; $-3(2)-3+2(-1)=-11$ ✓; $-2(2)+3+2(-1)=-3$ ✓.

Exercício 3 — Número de soluções

a) $\begin{cases}x+y=3\\2x+2y=6\end{cases}$

$$\left[\begin{array}{rr|r}1&1&3\\2&2&6\end{array}\right]\xrightarrow{L_2\leftarrow L_2-2L_1}\left[\begin{array}{rr|r}1&1&3\\0&0&0\end{array}\right]$$
A segunda linha é nula ($0=0$): há apenas 1 equação independente para 2 incógnitas. 
Infinitas soluções: $x=3-t,\ y=t,\ t\in\mathbb{R}$. ($\text{posto}(A)=\text{posto}([A|b])=1<2$)

b) $\begin{cases}x+y=3\\2x+2y=7\end{cases}$

$$\left[\begin{array}{rr|r}1&1&3\\2&2&7\end{array}\right]\xrightarrow{L_2\leftarrow L_2-2L_1}\left[\begin{array}{rr|r}1&1&3\\0&0&1\end{array}\right]$$
A segunda linha representa $0=1$, impossível. Nenhuma solução (sistema inconsistente). ($\text{posto}(A)=1<\text{posto}([A|b])=2$)

c) $\begin{cases}x+y=3\\2x-y=0\end{cases}$

$$\left[\begin{array}{rr|r}1&1&3\\2&-1&0\end{array}\right]\xrightarrow{L_2\leftarrow L_2-2L_1}\left[\begin{array}{rr|r}1&1&3\\0&-3&-6\end{array}\right]$$
$-3y=-6\Rightarrow y=2$; $x=3-2=1$. Solução única: $(x,y)=(1,2)$. ($\text{posto}(A)=\text{posto}([A|b])=2=n$)

Verificação computacional pelo critério dos postos (Rouché–Capelli):

In [3]:
def classificar(A, b):
    # Classifica o sistema comparando posto(A), posto([A|b]) e o número de incógnitas n
    A = np.array(A, dtype=float); b = np.array(b, dtype=float)
    n = A.shape[1]
    rA  = np.linalg.matrix_rank(A)
    rAb = np.linalg.matrix_rank(np.column_stack([A, b]))
    if rA < rAb:
        tipo = "nenhuma solução (inconsistente)"
    elif rA == n:
        tipo = "solução única"
    else:
        tipo = "infinitas soluções"
    return rA, rAb, tipo

sistemas = {
    "a)": ([[1, 1], [2,  2]], [3, 6]),
    "b)": ([[1, 1], [2,  2]], [3, 7]),
    "c)": ([[1, 1], [2, -1]], [3, 0]),
}
for nome, (A, b) in sistemas.items():
    rA, rAb, tipo = classificar(A, b)
    print(f"{nome} posto(A)={rA}, posto([A|b])={rAb}  ->  {tipo}")

a) posto(A)=1, posto([A|b])=1  ->  infinitas soluções
b) posto(A)=1, posto([A|b])=2  ->  nenhuma solução (inconsistente)
c) posto(A)=2, posto([A|b])=2  ->  solução única


Interpretação: os resultados computacionais confirmam a análise manual. Geometricamente: em (a) as duas retas são coincidentes, em (b) são paralelas distintas e em (c) se cruzam em um único ponto.

Exercício 4 — Eliminação de Gauss sem pivoteamento

In [4]:
def gauss_sem_pivoteamento(A, b, verbose=False):
    '''Resolve Ax = b por eliminação de Gauss SEM pivoteamento.

    Parâmetros
    ----------
    A : array (n, n)  matriz dos coeficientes
    b : array (n,)    vetor independente
    verbose : se True, imprime a matriz aumentada a cada etapa

    Retorna
    -------
    x : array (n,)    solução calculada
    '''
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)

    # 1) Forma a matriz aumentada [A | b]
    Ab = np.column_stack([A, b])
    if verbose:
        print("Matriz aumentada inicial:\n", Ab, "\n")

    # 2) Eliminação: zera os elementos abaixo de cada pivô
    for k in range(n - 1):
        if Ab[k, k] == 0:
            raise ZeroDivisionError(f"Pivô nulo na posição ({k},{k}): "
                                    "é necessário pivoteamento.")
        for i in range(k + 1, n):
            m = Ab[i, k] / Ab[k, k]           # multiplicador m_ik
            Ab[i, k:] = Ab[i, k:] - m * Ab[k, k:]   # L_i <- L_i - m * L_k
            Ab[i, k] = 0.0                    # evita resíduo de arredondamento
        if verbose:
            print(f"Após eliminar a coluna {k+1}:\n", Ab, "\n")

    if Ab[n-1, n-1] == 0:
        raise ZeroDivisionError("Pivô nulo no último elemento: sistema singular.")

    # 3) Substituição regressiva
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        soma = np.dot(Ab[i, i+1:n], x[i+1:n])
        x[i] = (Ab[i, n] - soma) / Ab[i, i]
    return x

Teste com o sistema do Exercício 2 e comparação com numpy.linalg.solve:

In [5]:
A2 = np.array([[ 2,  1, -1],
               [-3, -1,  2],
               [-2,  1,  2]], dtype=float)
b2 = np.array([8, -11, -3], dtype=float)

x_gauss = gauss_sem_pivoteamento(A2, b2, verbose=True)
x_numpy = np.linalg.solve(A2, b2)

print("Solução (Gauss implementado):", x_gauss)
print("Solução (numpy.linalg.solve):", x_numpy)
print("Diferença máxima |x_gauss - x_numpy| =", np.max(np.abs(x_gauss - x_numpy)))
print("Resíduo ||A x - b||∞ =", np.max(np.abs(A2 @ x_gauss - b2)))

Matriz aumentada inicial:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]] 

Após eliminar a coluna 1:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]] 

Após eliminar a coluna 2:
 [[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]] 

Solução (Gauss implementado): [ 2.  3. -1.]
Solução (numpy.linalg.solve): [ 2.  3. -1.]
Diferença máxima |x_gauss - x_numpy| = 2.886579864025407e-15
Resíduo ||A x - b||∞ = 0.0


Interpretação: as matrizes aumentadas impressas coincidem com as etapas feitas à mão no Exercício 2 (após a etapa 1: linhas $[0,\ 0.5,\ 0.5\,|\,1]$ e $[0,\ 2,\ 1\,|\,5]$; após a etapa 2: $[0,\ 0,\ -1\,|\,1]$). A solução $(2,3,-1)$ concorda com a manual e com o numpy.linalg.solve (que usa LU com pivoteamento parcial) a menos de erro de arredondamento da ordem de $10^{-15}$. Neste sistema os pivôs ($2$, $0.5$, $-1$) nunca se anulam, por isso o método sem pivoteamento funciona; em geral, um pivô nulo ou muito pequeno exigiria pivoteamento.

Exercício 5 — Modelo de balanço térmico

$$\begin{bmatrix}4&-1&0\\-1&4&-1\\0&-1&3\end{bmatrix}\begin{bmatrix}T_1\\T_2\\T_3\end{bmatrix}=\begin{bmatrix}15\\10\\10\end{bmatrix}$$

a) Resolução manual

Matriz aumentada:
$$\left[\begin{array}{rrr|r}4&-1&0&15\\-1&4&-1&10\\0&-1&3&10\end{array}\right]$$

Etapa 1 — pivô $4$; $m_{21}=-1/4$, $m_{31}=0$: $L_2\leftarrow L_2+\tfrac14L_1$
$$\left[\begin{array}{rrr|r}4&-1&0&15\\0&\tfrac{15}{4}&-1&\tfrac{55}{4}\\0&-1&3&10\end{array}\right]$$

Etapa 2 — pivô $\tfrac{15}{4}$; $m_{32}=-1/(15/4)=-\tfrac{4}{15}$: $L_3\leftarrow L_3+\tfrac{4}{15}L_2$
$$\left[\begin{array}{rrr|r}4&-1&0&15\\0&\tfrac{15}{4}&-1&\tfrac{55}{4}\\0&0&\tfrac{41}{15}&\tfrac{41}{3}\end{array}\right]$$
(pois $3-\tfrac{4}{15}=\tfrac{41}{15}$ e $10+\tfrac{4}{15}\cdot\tfrac{55}{4}=10+\tfrac{11}{3}=\tfrac{41}{3}$)

Substituição regressiva:
- $\tfrac{41}{15}T_3=\tfrac{41}{3}\Rightarrow T_3=5$
- $\tfrac{15}{4}T_2-5=\tfrac{55}{4}\Rightarrow \tfrac{15}{4}T_2=\tfrac{75}{4}\Rightarrow T_2=5$
- $4T_1-5=15\Rightarrow T_1=5$

$$\boxed{T_1=T_2=T_3=5}$$

Conferência: $4(5)-5=15$; $-5+20-5=10$; $-5+15=10$


b) Implementação em Python

In [6]:
A5 = np.array([[ 4, -1,  0],
               [-1,  4, -1],
               [ 0, -1,  3]], dtype=float)
b5 = np.array([15, 10, 10], dtype=float)

T_gauss = gauss_sem_pivoteamento(A5, b5, verbose=True)   # nossa implementação (Ex. 4)
T_numpy = np.linalg.solve(A5, b5)                        # referência

print("T (Gauss implementado):", T_gauss)
print("T (numpy.linalg.solve):", T_numpy)
print("Diferença máxima:", np.max(np.abs(T_gauss - T_numpy)))
print("Resíduo ||A T - b||∞ =", np.max(np.abs(A5 @ T_gauss - b5)))

Matriz aumentada inicial:
 [[ 4. -1.  0. 15.]
 [-1.  4. -1. 10.]
 [ 0. -1.  3. 10.]] 

Após eliminar a coluna 1:
 [[ 4.   -1.    0.   15.  ]
 [ 0.    3.75 -1.   13.75]
 [ 0.   -1.    3.   10.  ]] 

Após eliminar a coluna 2:
 [[ 4.       -1.        0.       15.      ]
 [ 0.        3.75     -1.       13.75    ]
 [ 0.        0.        2.733333 13.666667]] 

T (Gauss implementado): [5. 5. 5.]
T (numpy.linalg.solve): [5. 5. 5.]
Diferença máxima: 0.0
Resíduo ||A T - b||∞ = 0.0


Interpretação: a solução numérica $T_1=T_2=T_3=5$ coincide com a manual. A matriz é tridiagonal e diagonalmente dominante (com dominância estrita na 1ª e na 3ª linha), o que garante pivôs não nulos e estabilidade da eliminação sem pivoteamento. Fisicamente, as três temperaturas se igualam em equilíbrio porque as fontes (lado direito) são compatíveis com os acoplamentos da rede: $15 = 4\cdot5-5$, $10=-5+20-5$, $10=-5+15$.